POST {{endpoint}}/foodCart/create

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 if (response.status === 200) {
   client.global.set("foodCartId",response.body);
 }
 %}

###

GET {{endpoint}}/foodCart/{{foodCartId}}

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###

POST {{endpoint}}/foodCart/{{foodCartId}}/select/{{productId}}/quantity/{{quantity}}

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###

POST {{endpoint}}/foodCart/{{foodCartId}}/deselect/{{productId}}/quantity/{{quantity}}

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
